#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/scripts

# polkit agent
if [[ ! 'pidof polkit-gnome-authentication-agent-1' ]];then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
polkit.addRule(function(action, subject) {
    if (action.id == "org.freedesktop.timeshift.run" &&
        subject.isInGroup("wheel")) {
        return polkit.Result.YES;
    }
});

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Xauthority
${SCRIPTSDIR}/xauthority &
